# Generated by Django 4.0.3 on 2022-04-13 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentData',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='TeacherData',
            new_name='Teacher',
        ),
    ]
