# Generated by Django 4.0.3 on 2022-04-22 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='date_submit',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
