# Generated by Django 4.0.3 on 2022-04-13 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_details', '0002_rename_studentdata_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(5, '5'), (6, '6'), (7, '7')], default='5')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='std',
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to='school_details.grade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teaching_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_details.grade'),
        ),
        migrations.DeleteModel(
            name='Std',
        ),
    ]
