# Generated by Django 4.0.3 on 2022-04-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_details', '0002_alter_customuser_first_name_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='category',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], default='Teacher', max_length=50),
        ),
    ]
