# Generated by Django 4.0.3 on 2022-04-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_details', '0003_alter_teacher_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('user', 'subject')},
        ),
    ]
