# Generated by Django 4.0.3 on 2022-04-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_details', '0003_grade_remove_student_std_student_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teaching_in',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_in',
            field=models.ManyToManyField(to='school_details.grade'),
        ),
    ]
