# Generated by Django 4.0.3 on 2022-04-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_details', '0004_alter_mark_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.PositiveIntegerField(),
        ),
    ]
