# Generated by Django 4.0.3 on 2022-04-19 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_details', '0004_remove_teacher_teaching_in_teacher_teaching_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teaching_in',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_in',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='school_details.grade'),
            preserve_default=False,
        ),
    ]
