# Generated by Django 4.0.3 on 2022-04-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_details', '0006_remove_teacher_teaching_in_teacher_teaching_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dob',
            field=models.DateField(auto_now=True),
        ),
    ]
